mode:
  - "transparent@8080"
  - "reverse:dns://1.1.1.1@53"
showhost: true

# Web
web_host: "127.0.0.1"
web_port: 8081

scripts:
  - "/config/scripts/main.py"
  - "/config/scripts/inject.py"
  - "/config/scripts/customUI.py"
